### ISSUE TITLE
Assert error introduced in packaging

### ISSUE THREAD

**Issue by stonneau** [humanoid-path-planner/hpp-rbprm#17]
Here: https://github.com/humanoid-path-planner/hpp-rbprm/blob/73b147c24c38ca00bcaafa5ba1e62302159751b7/src/rbprm-validation.cc#L126

From commit:
See https://github.com/humanoid-path-planner/hpp-rbprm/commit/9a8e3bad74e82c1bb7658b265fba612a9adf36d8#diff-52ca23fe7489a0686f25347dffbefe48R124

This object creation causes a failed assert in hpp-pinocchio here:
https://github.com/humanoid-path-planner/hpp-pinocchio/blob/ce51b09ccfb99d25f340c449f2b63d8a5dac4ccb/src/collision-object.cc#L119

Due to this call:
https://github.com/humanoid-path-planner/hpp-pinocchio/blob/ce51b09ccfb99d25f340c449f2b63d8a5dac4ccb/src/collision-object.cc#L63

I don't understand exactly the line. There is no direct connection here between the affIdx and the robot, 
so I don't understand why this call was changed with respect to what was there before.

@nim65s  Can you bring a light to this commit ? Thanks !

**Comment by nim65s** [comment]
@pFernbach found that yesterday, and explained some tests failure, but we didn't share, sorry :/

In short, I don't understand how those changes got there, or how I could commit that, nor why, moreover in a packaging commit. This have to be reverted, and for the release I added a patch on robotpkg : https://github.com/nim65s/robotpkg-wip/commit/f3bd52c781db44b2afb6efea948a54efdb2834e0

Sorry for this ^^"

**Comment by stonneau** [comment]
Ok thanks !

**Comment by stonneau** [comment]
solved in https://github.com/humanoid-path-planner/hpp-rbprm/commit/67c94605b828d7fd5d77c6aa9339897490fae962
