### ISSUE TITLE
Test kinodynamic fails

### ISSUE THREAD

**Issue by florent-lamiraux** [humanoid-path-planner/hpp-rbprm#35]
I am trying to understand why test kinodynamic fails on recent devel branches.

I ran the test in valgrind and got an "Invalid read of size 8" at the following line:
https://github.com/humanoid-path-planner/hpp-rbprm/blob/0cdb2ee8320af0752a1face9c3e887735d360d1d/src/utils/algorithms.cc#L424

This line is indeed suspicious since iterator e runs until plan.end () is reached, but in this case, `e+1` should be out of bound.
Surprisingly, adding `assert (e+1 != plan.end ())` did not make the program fail.

**Comment by pFernbach** [comment]
Thanks for catching this error, I do not understand why the assert never fail ...

What was your error with the kinodynamic test ? It may be unrelated to this. With the devel versions of hpp of two days ago it work on my computer.

**Comment by florent-lamiraux** [comment]
The test fails on gepgitlab. The difference of behavior might be due to some uninitialized variable.
https://gepgitlab.laas.fr/humanoid-path-planner/hpp-doc/-/jobs/17304

**Comment by pFernbach** [comment]
https://gepgitlab.laas.fr/humanoid-path-planner/hpp-doc/pipelines/4098

PR https://github.com/humanoid-path-planner/hpp-rbprm/pull/36 seems to fix the issue with the kinodynamic test with the devel branch.

**Comment by florent-lamiraux** [comment]
Thank you.
