### ISSUE TITLE
ProblemSolver::latest has been removed

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/hpp-rbprm#55]
Hi,

https://github.com/humanoid-path-planner/hpp-rbprm/blob/0f15334d452e4a7c999302bdec0869b0cf674f52/tests/tools-obstacle.hh#L181

And following lines are using `ProblemSolver::latest()`, which as been removed in https://github.com/humanoid-path-planner/hpp-core/pull/183

This prevent the next release, can someone fix this ?

**Comment by stonneau** [comment]
@florent-lamiraux is there any workaround to retrieve the latest ?
@pFernbach I am sorry but I am traveling and will be in London all of tomorrow,
I can't look at it before Friday. Would you have the time to take a look ?

**Comment by jmirabel** [comment]
I won't have time before monday.

The easy fix is to pass a ProblemSolverPtr_t as an argument to all the method of BindShooter and modifying the few boost::bind use so that the argument is correctly set.

I am surprised I missed that one. I thought I did compile and check rbprm with this...

**Comment by pFernbach** [comment]
Done, thanks for the explanation @jmirabel .
